name: Build Windows Installer

on:
  workflow_dispatch: # Permite que você clique em um botão no GitHub para gerar o instalador quando quiser

jobs:
  msi-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Latest Release Artifact
        uses: robinraju/release-downloader@v1.11
        with:
          latest: true
          fileName: "voices-windows.zip" # Nome do zip gerado pela sua outra pipeline

      - name: Extract Release Zip
        run: |
          mkdir SourceFiles
          # Descompacta o ZIP dentro de uma subpasta chamada voices.dist para manter a estrutura original
          Expand-Archive -Path voices-windows.zip -DestinationPath SourceFiles

      - name: Harvest Directory Files (WiX heat)
        run: |
          # Adicionamos -b SourceFiles para o WiX saber exatamente onde ler fisicamente as DLLs
          heat.exe dir SourceFiles\voices.dist -cg AppFilesGroup -dr APPLICATIONFOLDER -sreg -sfrag -srd -gg -b SourceFiles\voices.dist -out files.wxs

      - name: Compile Installer (WiX candle & light)
        run: |
          candle.exe voices.wxs files.wxs
          light.exe -ext WixUIExtension voices.wixobj files.wixobj -o VoicesInstaller.msi

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Voices-Windows-Installer
          path: VoicesInstaller.msi
